# Setup
title:               Project RAINDROP
tagline:             'from UCLouvain and UNamur'
description:         'Research project RAINDROP on Cloud/Edge Continuum'
url:                 
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Yinan CAO
  url:               
  email:             yinan.cao@uclouvain.be

# Gems
plugins:
  - jekyll-paginate

# Custom vars
google_analytics_id: #UA-XXXX-Y
