# Setup
title:               Project RAINDROP
tagline:             'from UCLouvain and UNamur'
description:         'RAINDROP aims to address in a unique way the challenge of building, deploying, and operating applications on upcoming cloud infrastructures formed of a continuum of core (data centers) and edge resources.'
url:                 'https://sites.uclouvain.be'
baseurl:             '/raindrop'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Yinan CAO
  url:               
  email:             yinan.cao@uclouvain.be

# Gems
plugins:
  - jekyll-paginate

# Custom vars
google_analytics_id: #UA-XXXX-Y
